/* XY-C1/C5 */

#define BOARD_PID		"ER-X Pro"
#define BOARD_NAME		"ER-X Pro"
#define BOARD_DESC		"ER-X Pro Router"
#define BOARD_VENDOR_NAME	"Modify by lastkiss"
#define BOARD_VENDOR_URL	"https://"
#define BOARD_MODEL_URL		"https://"
#define BOARD_BOOT_TIME		30
#define BOARD_FLASH_TIME	120
#undef BOARD_GPIO_BTN_FN1
#define BOARD_GPIO_BTN_RESET	18
#undef  BOARD_GPIO_BTN_WPS
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#undef  BOARD_GPIO_LED_SW2G
#undef  BOARD_GPIO_LED_SW5G
#define  BOARD_GPIO_LED_POWER	31 // NA
#define  BOARD_GPIO_LED_LAN	7 //SYS
#define BOARD_GPIO_LED_WAN	8 //WORK
#undef BOARD_GPIO_LED_USB	
#undef BOARD_GPIO_LED_ROUTER
#define BOARD_HAS_5G_11AC	0
#define BOARD_NUM_ANT_5G_TX	2
#define BOARD_NUM_ANT_5G_RX	2
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
#define BOARD_NUM_UPHY_USB3	1
#define BOARD_GPIO_PWR_USB	11
#define BOARD_GPIO_PWR_USB_ON	1
#define BOARD_USB_PORT_SWAP	0
